import { createHash, scryptSync, timingSafeEqual } from "crypto";

import type { Auth } from "firebase-admin/auth";
import {
  FieldValue,
  Timestamp,
  type DocumentReference,
  type DocumentData,
  type Firestore,
  type QueryDocumentSnapshot,
} from "firebase-admin/firestore";
import { defineSecret } from "firebase-functions/params";
import * as logger from "firebase-functions/logger";
import { HttpsError, onCall } from "firebase-functions/v2/https";

import { withAppCheck } from "./appCheckPolicy";
import { buildDirectRoomId } from "./matchIdentity";

export const PLAY_REVIEW_PARTITION = "play_review";
export const PLAY_REVIEW_ACCOUNT_TYPE = "google_play_review";
export const PLAY_REVIEW_FIXTURE_ACCOUNT_TYPE = "google_play_fixture";
export const PLAY_REVIEWER_UID = "play-reviewer-v1";
export const PLAY_REVIEW_FIXTURE_UIDS = [
  "play-fixture-a-02",
  "play-fixture-a-03",
  "play-fixture-b-01",
  "play-fixture-b-02",
  "play-fixture-b-03",
  "play-fixture-b-04",
  "play-fixture-b-05",
  "play-fixture-b-06",
] as const;
export const PLAY_REVIEW_FEED_UIDS = [
  "play-fixture-b-01",
  "play-fixture-b-02",
  "play-fixture-b-03",
  "play-fixture-b-04",
  "play-fixture-b-05",
  "play-fixture-b-06",
] as const;
export const PLAY_REVIEW_ALL_UIDS = [
  PLAY_REVIEWER_UID,
  ...PLAY_REVIEW_FIXTURE_UIDS,
] as const;

const PLAY_REVIEW_LOGIN_ID = defineSecret("PLAY_REVIEW_LOGIN_ID");
const PLAY_REVIEW_PASSWORD_SCRYPT = defineSecret(
  "PLAY_REVIEW_PASSWORD_SCRYPT",
);
const PLAY_REVIEW_FIREBASE_UID = defineSecret("PLAY_REVIEW_FIREBASE_UID");
const PLAY_REVIEW_ENABLED = defineSecret("PLAY_REVIEW_ENABLED");

const LOGIN_WINDOW_MS = 15 * 60 * 1000;
const LOGIN_MAX_FAILURES = 8;
const SCRYPT_KEY_LENGTH = 32;
const REVIEW_MEETING_ID = "play-review-blind-meeting-v1";
const REVIEW_GROUP_ROOM_ID = `blind_${REVIEW_MEETING_ID}`;
const REVIEW_BAMBOO_POSTS_COLLECTION = "playReviewBambooPosts";
const REVIEW_BAMBOO_POST_AUTHORS_COLLECTION = "playReviewBambooPostAuthors";
const REVIEW_BAMBOO_COMMENT_AUTHORS_COLLECTION =
  "playReviewBambooCommentAuthors";
const REVIEW_BAMBOO_FIXTURE_VERSION = 2;

type ReviewAuth = {
  uid?: string;
  token?: Record<string, unknown>;
} | null | undefined;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readCallableData(value: unknown): Record<string, unknown> {
  return isRecord(value) ? value : {};
}

function normalizedText(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function fixedTimeTextEqual(left: string, right: string): boolean {
  const leftDigest = createHash("sha256").update(left, "utf8").digest();
  const rightDigest = createHash("sha256").update(right, "utf8").digest();
  return timingSafeEqual(leftDigest, rightDigest);
}

/**
 * Secret format generated by scripts/generate_play_review_password_hash.js:
 * `scrypt-v1:<salt-base64>:<derived-key-base64>`.
 */
export function verifyPlayReviewPassword(
  password: string,
  encodedSecret: string,
): boolean {
  const [version, saltBase64, expectedBase64, extra] = encodedSecret.split(":");
  if (
    version !== "scrypt-v1" ||
    !saltBase64 ||
    !expectedBase64 ||
    extra !== undefined
  ) {
    return false;
  }
  try {
    const salt = Buffer.from(saltBase64, "base64");
    const expected = Buffer.from(expectedBase64, "base64");
    if (salt.length < 16 || expected.length !== SCRYPT_KEY_LENGTH) return false;
    const actual = scryptSync(password, salt, SCRYPT_KEY_LENGTH, {
      N: 16384,
      r: 8,
      p: 1,
      maxmem: 64 * 1024 * 1024,
    });
    return timingSafeEqual(actual, expected);
  } catch {
    return false;
  }
}

export function isPlayReviewUserData(
  data: Record<string, unknown> | null | undefined,
): boolean {
  return !!data &&
    data.accountType === PLAY_REVIEW_ACCOUNT_TYPE &&
    data.dataPartition === PLAY_REVIEW_PARTITION &&
    data.reviewAccess === true &&
    data.reviewProfileReady === true;
}

export function isPlayReviewFixtureData(
  data: Record<string, unknown> | null | undefined,
): boolean {
  return !!data &&
    data.accountType === PLAY_REVIEW_FIXTURE_ACCOUNT_TYPE &&
    data.dataPartition === PLAY_REVIEW_PARTITION &&
    data.reviewFixtureEnabled === true;
}

/**
 * Fixtures intentionally have `loginDisabled: true` so they cannot become
 * real sign-in accounts. That flag must not prevent the one fixed reviewer
 * session from opening a review-only direct chat with them.
 */
export function canPlayReviewUserOpenDirectChatWithFixture(
  userData: Record<string, unknown> | null | undefined,
  partnerData: Record<string, unknown> | null | undefined,
): boolean {
  return isPlayReviewUserData(userData) && isPlayReviewFixtureData(partnerData);
}

export function dataPartitionOf(
  data: Record<string, unknown> | null | undefined,
): "production" | "play_review" | "invalid" {
  const value = data?.dataPartition;
  if (value === undefined || value === null || value === "production") {
    return "production";
  }
  return value === PLAY_REVIEW_PARTITION ? PLAY_REVIEW_PARTITION : "invalid";
}

function kstDateKey(now = new Date()): string {
  const kst = new Date(now.getTime() + 9 * 60 * 60 * 1000);
  const year = kst.getUTCFullYear().toString();
  const month = (kst.getUTCMonth() + 1).toString().padStart(2, "0");
  const day = kst.getUTCDate().toString().padStart(2, "0");
  return `${year}${month}${day}`;
}

function kstIsoDate(now = new Date()): string {
  const key = kstDateKey(now);
  return `${key.slice(0, 4)}-${key.slice(4, 6)}-${key.slice(6, 8)}`;
}

function reviewIpHash(ip: string): string {
  return createHash("sha256")
    .update(`seolleyeon-play-review-login-v1:${ip || "unknown"}`, "utf8")
    .digest("hex");
}

async function assertLoginAttemptAllowed(
  firestore: Firestore,
  ipHash: string,
): Promise<void> {
  const ref = firestore.collection("playReviewRateLimits").doc(ipHash);
  const snap = await ref.get();
  if (!snap.exists) return;
  const windowStartedAt = snap.get("windowStartedAt");
  const failures = Number(snap.get("failures") ?? 0);
  if (
    windowStartedAt instanceof Timestamp &&
    Date.now() - windowStartedAt.toMillis() < LOGIN_WINDOW_MS &&
    failures >= LOGIN_MAX_FAILURES
  ) {
    throw new HttpsError(
      "resource-exhausted",
      "Review sign-in is temporarily unavailable. Try again later.",
    );
  }
}

async function recordLoginFailure(
  firestore: Firestore,
  ipHash: string,
): Promise<void> {
  const ref = firestore.collection("playReviewRateLimits").doc(ipHash);
  await firestore.runTransaction(async (tx) => {
    const snap = await tx.get(ref);
    const started = snap.get("windowStartedAt");
    const active = started instanceof Timestamp &&
      Date.now() - started.toMillis() < LOGIN_WINDOW_MS;
    tx.set(ref, {
      failures: active ? Number(snap.get("failures") ?? 0) + 1 : 1,
      windowStartedAt: active ? started : FieldValue.serverTimestamp(),
      lastFailedAt: FieldValue.serverTimestamp(),
    }, { merge: false });
  });
}

async function clearLoginFailures(
  firestore: Firestore,
  ipHash: string,
): Promise<void> {
  await firestore.collection("playReviewRateLimits").doc(ipHash).delete()
    .catch(() => undefined);
}

export async function resolvePlayReviewUser(
  firestore: Firestore,
  auth: ReviewAuth,
): Promise<{ userId: string; data: Record<string, unknown> }> {
  const uid = normalizedText(auth?.uid);
  if (!uid || uid !== PLAY_REVIEWER_UID) {
    throw new HttpsError("permission-denied", "Play review access is required.");
  }
  if (
    auth?.token?.playReviewer !== true ||
    auth.token.dataPartition !== PLAY_REVIEW_PARTITION ||
    auth.token.appSession !== true
  ) {
    throw new HttpsError("permission-denied", "Play review access is required.");
  }
  const snap = await firestore.collection("users").doc(uid).get();
  const data = (snap.data() ?? {}) as Record<string, unknown>;
  if (!snap.exists || !isPlayReviewUserData(data)) {
    throw new HttpsError("failed-precondition", "Review profile is unavailable.");
  }
  return { userId: uid, data };
}

async function validateReviewFixtures(firestore: Firestore): Promise<void> {
  const refs = PLAY_REVIEW_FIXTURE_UIDS.flatMap((uid) => [
    firestore.collection("users").doc(uid),
    firestore.collection("publicProfiles").doc(uid),
  ]);
  const snaps = await firestore.getAll(...refs);
  for (let index = 0; index < snaps.length; index += 2) {
    const user = snaps[index];
    const profile = snaps[index + 1];
    const expectedUid = PLAY_REVIEW_FIXTURE_UIDS[index / 2];
    if (
      user.id !== expectedUid ||
      profile.id !== expectedUid ||
      !user.exists ||
      !profile.exists ||
      !isPlayReviewFixtureData(user.data() as Record<string, unknown>) ||
      !isPlayReviewFixtureData(profile.data() as Record<string, unknown>)
    ) {
      throw new HttpsError(
        "failed-precondition",
        "Review fixtures are incomplete. Contact the app developer.",
      );
    }
  }
}

function allIdsAreReviewOnly(value: unknown): boolean {
  if (!Array.isArray(value) || value.length === 0) return false;
  const allowed = new Set<string>(PLAY_REVIEW_ALL_UIDS);
  return value.every((id) => typeof id === "string" && allowed.has(id));
}

async function deleteValidatedReviewDocs(
  firestore: Firestore,
  docs: QueryDocumentSnapshot<DocumentData>[],
  participantField?: string,
): Promise<void> {
  const refs = [];
  for (const doc of docs) {
    const data = doc.data() as Record<string, unknown>;
    if (data.dataPartition !== PLAY_REVIEW_PARTITION) continue;
    if (participantField && !allIdsAreReviewOnly(data[participantField])) {
      logger.error("Refusing mixed-partition review reset", {
        path: doc.ref.path,
      });
      throw new HttpsError("internal", "Review data isolation check failed.");
    }
    refs.push(doc.ref);
  }
  for (let start = 0; start < refs.length; start += 400) {
    const batch = firestore.batch();
    for (const ref of refs.slice(start, start + 400)) batch.delete(ref);
    await batch.commit();
  }
}

function isReviewOnlyUid(value: unknown): value is string {
  return typeof value === "string" &&
    (PLAY_REVIEW_ALL_UIDS as readonly string[]).includes(value);
}

function assertReviewBambooDocument(
  data: Record<string, unknown>,
  path: string,
  idField: "authorId" | "ownerUid" | "userId",
): void {
  if (
    data.dataPartition !== PLAY_REVIEW_PARTITION ||
    !isReviewOnlyUid(data[idField])
  ) {
    logger.error("Refusing unsafe review Bamboo reset", { path, idField });
    throw new HttpsError("internal", "Review data isolation check failed.");
  }
}

async function deleteRefsInBatches(
  firestore: Firestore,
  refs: DocumentReference[],
): Promise<void> {
  for (let start = 0; start < refs.length; start += 400) {
    const batch = firestore.batch();
    for (const ref of refs.slice(start, start + 400)) batch.delete(ref);
    await batch.commit();
  }
}

async function resetReviewBambooArtifacts(firestore: Firestore): Promise<void> {
  const [posts, postOwners, commentOwners] = await Promise.all([
    firestore.collection(REVIEW_BAMBOO_POSTS_COLLECTION).get(),
    firestore.collection(REVIEW_BAMBOO_POST_AUTHORS_COLLECTION).get(),
    firestore.collection(REVIEW_BAMBOO_COMMENT_AUTHORS_COLLECTION).get(),
  ]);
  const refs: DocumentReference[] = [];

  for (const post of posts.docs) {
    assertReviewBambooDocument(
      post.data() as Record<string, unknown>,
      post.ref.path,
      "authorId",
    );
    const [comments, likes] = await Promise.all([
      post.ref.collection("comments").get(),
      post.ref.collection("likes").get(),
    ]);
    for (const like of likes.docs) {
      assertReviewBambooDocument(
        like.data() as Record<string, unknown>,
        like.ref.path,
        "userId",
      );
      refs.push(like.ref);
    }
    for (const comment of comments.docs) {
      assertReviewBambooDocument(
        comment.data() as Record<string, unknown>,
        comment.ref.path,
        "authorId",
      );
      const commentLikes = await comment.ref.collection("likes").get();
      for (const like of commentLikes.docs) {
        assertReviewBambooDocument(
          like.data() as Record<string, unknown>,
          like.ref.path,
          "userId",
        );
        refs.push(like.ref);
      }
      refs.push(comment.ref);
    }
    refs.push(post.ref);
  }
  for (const mapping of [...postOwners.docs, ...commentOwners.docs]) {
    assertReviewBambooDocument(
      mapping.data() as Record<string, unknown>,
      mapping.ref.path,
      "ownerUid",
    );
    refs.push(mapping.ref);
  }
  await deleteRefsInBatches(firestore, refs);
}

async function resetReviewArtifacts(firestore: Firestore): Promise<void> {
  const [fromInteractions, toInteractions, matches, rooms, reports] =
    await Promise.all([
      firestore.collection("interactions")
        .where("fromUserId", "==", PLAY_REVIEWER_UID).get(),
      firestore.collection("interactions")
        .where("toUserId", "==", PLAY_REVIEWER_UID).get(),
      firestore.collection("matches")
        .where("userIds", "array-contains", PLAY_REVIEWER_UID).get(),
      firestore.collection("chat_rooms")
        .where("participantIds", "array-contains", PLAY_REVIEWER_UID).get(),
      firestore.collection("reports")
        .where("reporterId", "==", PLAY_REVIEWER_UID).get(),
    ]);

  const interactionDocs = new Map<string, QueryDocumentSnapshot<DocumentData>>();
  for (const doc of [...fromInteractions.docs, ...toInteractions.docs]) {
    interactionDocs.set(doc.ref.path, doc);
  }
  // Subcollections survive parent deletion in Firestore. Validate every room
  // before clearing its messages so a corrupted mixed room aborts the reset.
  for (const room of rooms.docs) {
    const roomData = room.data() as Record<string, unknown>;
    if (roomData.dataPartition !== PLAY_REVIEW_PARTITION) continue;
    if (!allIdsAreReviewOnly(roomData.participantIds)) {
      throw new HttpsError("internal", "Review data isolation check failed.");
    }
    const messages = await room.ref.collection("messages").get();
    const messageBatch = firestore.batch();
    for (const message of messages.docs) messageBatch.delete(message.ref);
    if (!messages.empty) await messageBatch.commit();
  }
  const reviewMeetingRef = firestore.collection("blindMeetings").doc(REVIEW_MEETING_ID);
  const reviewMeeting = await reviewMeetingRef.get();
  if (reviewMeeting.exists) {
    const meetingData = (reviewMeeting.data() ?? {}) as Record<string, unknown>;
    if (
      meetingData.dataPartition !== PLAY_REVIEW_PARTITION ||
      !allIdsAreReviewOnly(meetingData.participantIds)
    ) {
      throw new HttpsError("internal", "Review data isolation check failed.");
    }
    for (const child of ["participants", "publicProfiles", "matchingResult"]) {
      const children = await reviewMeetingRef.collection(child).get();
      const childBatch = firestore.batch();
      for (const doc of children.docs) childBatch.delete(doc.ref);
      if (!children.empty) await childBatch.commit();
    }
  }
  await deleteValidatedReviewDocs(firestore, [...interactionDocs.values()]);
  await deleteValidatedReviewDocs(firestore, matches.docs, "userIds");
  await deleteValidatedReviewDocs(firestore, rooms.docs, "participantIds");
  await deleteValidatedReviewDocs(firestore, reports.docs);
  await resetReviewBambooArtifacts(firestore);

  const exactDeletes = [
    firestore.collection("blindMeetingApplications").doc(PLAY_REVIEWER_UID),
    firestore.collection("blindMeetings").doc(REVIEW_MEETING_ID),
    firestore.collection("chat_rooms").doc(REVIEW_GROUP_ROOM_ID),
    firestore.collection("users").doc(PLAY_REVIEWER_UID)
      .collection("recommendationRefreshes").doc(kstDateKey()),
  ];
  const batch = firestore.batch();
  for (const ref of exactDeletes) batch.delete(ref);
  for (const ownerUid of PLAY_REVIEW_ALL_UIDS) {
    for (const targetUid of PLAY_REVIEW_ALL_UIDS) {
      if (ownerUid === targetUid) continue;
      batch.delete(firestore.collection("blocks").doc(ownerUid)
        .collection("targets").doc(targetUid));
    }
  }
  await batch.commit();
}

function fixtureProfileSnapshot(data: Record<string, unknown>): Record<string, unknown> {
  const onboarding = isRecord(data.onboarding) ? data.onboarding : {};
  const interests = Array.isArray(onboarding.interests) ? onboarding.interests : [];
  return {
    userId: normalizedText(data.uid),
    nickname: normalizedText(data.nickname ?? onboarding.nickname),
    department: normalizedText(data.department ?? onboarding.department),
    mbti: normalizedText(data.mbti ?? onboarding.mbti),
    topInterestIds: interests.slice(0, 3),
    avatarSeed: normalizedText(data.uid),
    schoolVerified: true,
    safetyStampSummary: {
      completedMeetings: 0,
      allCheckinsCompleted: false,
      allCheckoutsCompleted: false,
    },
    oneLineIntro: normalizedText(
      onboarding.selfIntroduction ?? onboarding.bio ?? data.bio,
    ),
  };
}

async function seedReviewScenario(firestore: Firestore): Promise<void> {
  const profileRefs = PLAY_REVIEW_ALL_UIDS.map((uid) =>
    firestore.collection("publicProfiles").doc(uid)
  );
  const profileSnaps = await firestore.getAll(...profileRefs);
  const profiles = new Map<string, Record<string, unknown>>();
  for (const snap of profileSnaps) {
    if (!snap.exists) {
      throw new HttpsError("failed-precondition", "Review profile is unavailable.");
    }
    profiles.set(snap.id, snap.data() as Record<string, unknown>);
  }

  const teamA = [PLAY_REVIEWER_UID, "play-fixture-a-02", "play-fixture-a-03"];
  const teamB = [
    "play-fixture-b-01",
    "play-fixture-b-02",
    "play-fixture-b-03",
  ];
  const participants = [...teamA, ...teamB];
  const today = kstIsoDate();
  const now = FieldValue.serverTimestamp();
  const batch = firestore.batch();

  batch.set(firestore.collection("users").doc(PLAY_REVIEWER_UID), {
    heartBalance: 100,
    heartBalanceUpdatedAt: now,
    reviewSessionPreparedAt: now,
  }, { merge: true });

  batch.set(firestore.collection("interactions")
    .doc("play_review_pre_like_b02_to_reviewer"), {
    fromUserId: "play-fixture-b-02",
    toUserId: PLAY_REVIEWER_UID,
    action: "like",
    source: "play_review_seed",
    dataPartition: PLAY_REVIEW_PARTITION,
    createdAt: now,
  });

  batch.set(firestore.collection("blindMeetingApplications")
    .doc(PLAY_REVIEWER_UID), {
    userId: PLAY_REVIEWER_UID,
    status: "confirmed",
    stage: "matched",
    requestedDateKeys: [today],
    meetingId: REVIEW_MEETING_ID,
    partyMemberIds: teamA,
    dnaApplicationCompleted: true,
    heartCost: 0,
    heartChargeCount: 0,
    dataPartition: PLAY_REVIEW_PARTITION,
    reviewFixture: true,
    appliedAt: now,
    updatedAt: now,
  });

  batch.set(firestore.collection("blindMeetings").doc(REVIEW_MEETING_ID), {
    meetingType: "blindTasteMeeting",
    schemaVersion: 2,
    algorithmVersion: "play_review_v1",
    status: "chat_open",
    serverStatus: "chat_open",
    matchedDateKey: today,
    commonAvailableDateKeys: [today],
    teamAUserIds: teamA,
    teamBUserIds: teamB,
    participantIds: participants,
    waitlistIds: [],
    groupChatId: REVIEW_GROUP_ROOM_ID,
    isAlcoholFree: false,
    dataPartition: PLAY_REVIEW_PARTITION,
    reviewFixture: true,
    createdAt: now,
    confirmedAt: now,
  });

  for (const uid of participants) {
    const team = teamA.includes(uid) ? "teamA" : "teamB";
    batch.set(firestore.collection("blindMeetings").doc(REVIEW_MEETING_ID)
      .collection("participants").doc(uid), {
      userId: uid,
      team,
      teamId: team,
      status: "confirmed",
      attendanceConfirmation24h: "pending",
      attendanceConfirmation3h: "pending",
      checkedIn: false,
      checkedOut: false,
      dataPartition: PLAY_REVIEW_PARTITION,
      reviewFixture: true,
      confirmedAt: now,
    });
    batch.set(firestore.collection("blindMeetings").doc(REVIEW_MEETING_ID)
      .collection("publicProfiles").doc(uid), {
      ...fixtureProfileSnapshot(profiles.get(uid) ?? {}),
      dataPartition: PLAY_REVIEW_PARTITION,
      reviewFixture: true,
    });
  }

  const participantInfo: Record<string, unknown> = {};
  for (const uid of participants) {
    const profile = profiles.get(uid) ?? {};
    participantInfo[uid] = {
      nickname: normalizedText(profile.nickname),
      avatarUrl: normalizedText(profile.profileImageUrl),
    };
  }
  batch.set(firestore.collection("chat_rooms").doc(REVIEW_GROUP_ROOM_ID), {
    roomId: REVIEW_GROUP_ROOM_ID,
    roomType: "blind_meeting_group",
    type: "group",
    status: "active",
    writable: true,
    meetingId: REVIEW_MEETING_ID,
    participantIds: participants,
    participantInfo,
    dataPartition: PLAY_REVIEW_PARTITION,
    reviewFixture: true,
    lastMessage: "Google Play review 3:3 test room",
    createdAt: now,
    updatedAt: now,
    lastMessageAt: now,
  });
  batch.set(firestore.collection("chat_rooms").doc(REVIEW_GROUP_ROOM_ID)
    .collection("messages").doc("review_welcome"), {
    senderId: "system",
    type: "system",
    text: "리뷰용 3:3 미팅 채팅방입니다.",
    content: "리뷰용 3:3 미팅 채팅방입니다.",
    readBy: [],
    dataPartition: PLAY_REVIEW_PARTITION,
    createdAt: now,
  });
  batch.set(firestore.collection("playReviewSessions")
    .doc(PLAY_REVIEWER_UID), {
    fixtureVersion: REVIEW_BAMBOO_FIXTURE_VERSION,
    reviewerUid: PLAY_REVIEWER_UID,
    dataPartition: PLAY_REVIEW_PARTITION,
    preparedAt: now,
  });
  const reviewBambooPosts = [
    {
      postId: "review_bamboo_welcome",
      authorId: "play-fixture-b-01",
      category: "일상",
      content: "안녕하세요! 이 글과 댓글은 Google Play 심사용으로 준비된 합성 대나무숲 데이터입니다.",
      tags: ["심사", "안내"],
      likeCount: 1,
      commentCount: 1,
      score7d: 2,
    },
    {
      postId: "review_bamboo_campus",
      authorId: "play-fixture-a-02",
      category: "고민",
      content: "점심 메뉴 추천 받아요. 리뷰 계정에서도 글 작성, 좋아요, 댓글 기능을 확인할 수 있습니다.",
      tags: ["고민"],
      likeCount: 0,
      commentCount: 0,
      score7d: 0,
    },
    {
      postId: "review_bamboo_tip",
      authorId: "play-fixture-b-03",
      category: "질문",
      content: "대나무숲의 전체·인기·카테고리 탭과 상세 화면을 검토할 수 있도록 만든 합성 게시글입니다.",
      tags: ["기능확인"],
      likeCount: 0,
      commentCount: 0,
      score7d: 0,
    },
  ];
  for (const post of reviewBambooPosts) {
    batch.set(firestore.collection(REVIEW_BAMBOO_POSTS_COLLECTION)
      .doc(post.postId), {
      ...post,
      dataPartition: PLAY_REVIEW_PARTITION,
      reviewFixture: true,
      isDeleted: false,
      createdAt: now,
      updatedAt: now,
    });
    batch.set(firestore.collection(REVIEW_BAMBOO_POST_AUTHORS_COLLECTION)
      .doc(post.postId), {
      postId: post.postId,
      ownerUid: post.authorId,
      dataPartition: PLAY_REVIEW_PARTITION,
      reviewFixture: true,
      createdAt: now,
    });
  }
  batch.set(firestore.collection(REVIEW_BAMBOO_POSTS_COLLECTION)
    .doc("review_bamboo_welcome").collection("comments")
    .doc("review_bamboo_welcome_comment"), {
    commentId: "review_bamboo_welcome_comment",
    authorId: "play-fixture-b-02",
    content: "상세 화면에서 댓글과 좋아요도 확인해 주세요.",
    parentCommentId: null,
    likeCount: 0,
    isDeleted: false,
    dataPartition: PLAY_REVIEW_PARTITION,
    reviewFixture: true,
    createdAt: now,
    updatedAt: now,
  });
  batch.set(firestore.collection(REVIEW_BAMBOO_COMMENT_AUTHORS_COLLECTION)
    .doc("review_bamboo_welcome__review_bamboo_welcome_comment"), {
    postId: "review_bamboo_welcome",
    commentId: "review_bamboo_welcome_comment",
    ownerUid: "play-fixture-b-02",
    dataPartition: PLAY_REVIEW_PARTITION,
    reviewFixture: true,
    createdAt: now,
  });
  batch.set(firestore.collection(REVIEW_BAMBOO_POSTS_COLLECTION)
    .doc("review_bamboo_welcome").collection("likes")
    .doc("play-fixture-a-03"), {
    userId: "play-fixture-a-03",
    dataPartition: PLAY_REVIEW_PARTITION,
    reviewFixture: true,
    createdAt: now,
  });
  await batch.commit();
}

export function createPlayReviewAccessCallables(
  firestore: Firestore,
  authAdmin: Auth,
) {
  const secretOptions = withAppCheck({
    timeoutSeconds: 60,
    memory: "256MiB",
    secrets: [
      PLAY_REVIEW_LOGIN_ID,
      PLAY_REVIEW_PASSWORD_SCRYPT,
      PLAY_REVIEW_FIREBASE_UID,
      PLAY_REVIEW_ENABLED,
    ],
  });

  const signIn = onCall(secretOptions, async (request) => {
    const data = readCallableData(request.data);
    const loginId = normalizedText(data.loginId);
    const password = normalizedText(data.password);
    if (!loginId || loginId.length > 128 || !password || password.length > 256) {
      throw new HttpsError("invalid-argument", "Review credentials are required.");
    }

    const ipHash = reviewIpHash(request.rawRequest.ip ?? "unknown");
    await assertLoginAttemptAllowed(firestore, ipHash);

    const enabled = PLAY_REVIEW_ENABLED.value().trim().toLowerCase() === "true";
    const expectedUid = PLAY_REVIEW_FIREBASE_UID.value().trim();
    const valid = enabled &&
      expectedUid === PLAY_REVIEWER_UID &&
      fixedTimeTextEqual(loginId, PLAY_REVIEW_LOGIN_ID.value().trim()) &&
      verifyPlayReviewPassword(password, PLAY_REVIEW_PASSWORD_SCRYPT.value());
    if (!valid) {
      await recordLoginFailure(firestore, ipHash);
      throw new HttpsError("unauthenticated", "Review credentials are invalid.");
    }

    const userSnap = await firestore.collection("users").doc(expectedUid).get();
    const userData = (userSnap.data() ?? {}) as Record<string, unknown>;
    if (!userSnap.exists || !isPlayReviewUserData(userData)) {
      throw new HttpsError("failed-precondition", "Review profile is unavailable.");
    }
    await validateReviewFixtures(firestore);
    const authUser = await authAdmin.getUser(expectedUid).catch(() => null);
    if (!authUser || authUser.email || authUser.phoneNumber) {
      throw new HttpsError("failed-precondition", "Review auth account is invalid.");
    }
    await clearLoginFailures(firestore, ipHash);
    const customToken = await authAdmin.createCustomToken(expectedUid, {
      appSession: true,
      playReviewer: true,
      dataPartition: PLAY_REVIEW_PARTITION,
    });
    return { customToken, reviewerUid: expectedUid };
  });

  const prepareSession = onCall(withAppCheck({ timeoutSeconds: 60 }), async (request) => {
    const reviewer = await resolvePlayReviewUser(firestore, request.auth);
    await validateReviewFixtures(firestore);
    await resetReviewArtifacts(firestore);
    await seedReviewScenario(firestore);
    logger.info("Play review session prepared", { reviewerUid: reviewer.userId });
    return {
      ok: true,
      reviewerUid: reviewer.userId,
      fixtureVersion: REVIEW_BAMBOO_FIXTURE_VERSION,
      feedCandidateUids: [...PLAY_REVIEW_FEED_UIDS],
      blindMeetingId: REVIEW_MEETING_ID,
    };
  });

  const getFeed = onCall(withAppCheck(), async (request) => {
    const reviewer = await resolvePlayReviewUser(firestore, request.auth);
    const refs = PLAY_REVIEW_FEED_UIDS.map((uid) =>
      firestore.collection("publicProfiles").doc(uid)
    );
    const snaps = await firestore.getAll(...refs);
    const items = snaps.map((snap, index) => {
      const profile = (snap.data() ?? {}) as Record<string, unknown>;
      if (!snap.exists || !isPlayReviewFixtureData(profile)) {
        throw new HttpsError("failed-precondition", "Review feed is unavailable.");
      }
      return { uid: snap.id, rank: index + 1 };
    });
    await firestore.collection("playReviewEvents").doc(reviewer.userId)
      .collection("events").add({
        eventType: "feed_loaded",
        dataPartition: PLAY_REVIEW_PARTITION,
        createdAt: FieldValue.serverTimestamp(),
      });
    return {
      ok: true,
      dateKey: kstDateKey(),
      source: "play_review",
      items,
    };
  });

  const purchaseRefresh = onCall(withAppCheck(), async (request) => {
    const reviewer = await resolvePlayReviewUser(firestore, request.auth);
    const dateKey = kstDateKey();
    const userRef = firestore.collection("users").doc(reviewer.userId);
    const entitlementRef = userRef.collection("recommendationRefreshes").doc(dateKey);
    return firestore.runTransaction(async (tx) => {
      const [userSnap, existing] = await Promise.all([
        tx.get(userRef),
        tx.get(entitlementRef),
      ]);
      if (existing.exists) {
        return {
          ok: true,
          status: "already_purchased",
          dateKey,
          remainingHearts: Number(userSnap.get("heartBalance") ?? 0),
          displayCandidateUids: PLAY_REVIEW_FEED_UIDS.slice(3),
        };
      }
      const balance = Number(userSnap.get("heartBalance") ?? 0);
      if (!Number.isFinite(balance) || balance < 5) {
        throw new HttpsError("failed-precondition", "insufficient_hearts");
      }
      tx.update(userRef, {
        heartBalance: balance - 5,
        heartBalanceUpdatedAt: FieldValue.serverTimestamp(),
      });
      tx.create(entitlementRef, {
        status: "completed",
        product: "one_to_one_daily_refresh",
        heartCost: 5,
        displayCandidateUids: PLAY_REVIEW_FEED_UIDS.slice(3),
        dataPartition: PLAY_REVIEW_PARTITION,
        source: "play_review",
        completedAt: FieldValue.serverTimestamp(),
      });
      return {
        ok: true,
        status: "purchased",
        dateKey,
        remainingHearts: balance - 5,
        displayCandidateUids: PLAY_REVIEW_FEED_UIDS.slice(3),
      };
    });
  });

  return { signIn, prepareSession, getFeed, purchaseRefresh };
}

/** Server-side partition guard reused by normal triggers/callables. */
export function assertSameDataPartition(
  left: Record<string, unknown>,
  right: Record<string, unknown>,
): "production" | "play_review" {
  const leftPartition = dataPartitionOf(left);
  const rightPartition = dataPartitionOf(right);
  if (
    leftPartition === "invalid" ||
    rightPartition === "invalid" ||
    leftPartition !== rightPartition
  ) {
    throw new HttpsError("permission-denied", "Account partitions do not match.");
  }
  return leftPartition;
}

export function reviewDirectRoomId(partnerId: string): string {
  return buildDirectRoomId(PLAY_REVIEWER_UID, partnerId);
}
